on:
  push:
    branches: [ main ]
    # Sequence of patterns matched against refs/tags

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
      - name: Release
        uses: qcastel/github-actions-maven-release@v1.12.8
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          release-branch-name: "main"
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
